ReachFive/identity-ios-sdk

IdentitySdkCore/IdentitySdkCore.xcodeproj/project.pbxproj
IdentitySdkCore/IdentitySdkCore/Classes/ReachFive.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveApi.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePassword.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveProviders.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/ClientConfigResponse.swift
IdentitySdkGoogle/IdentitySdkGoogle/Classes/GoogleProvider.swift
Sandbox/Podfile.lock
Sandbox/Sandbox/LoginController.swift
Sandbox/Sandbox/SignupController.swift

Asana: https://app.asana.com/0/1128361015731305/1129994254353860

Use scope obtained from client config instead of default scopes

---

IdentitySdkCore.podspec
IdentitySdkCore/IdentitySdkCore/Classes/utils/DataRequest.swift
IdentitySdkCore/Podfile.lock
IdentitySdkFacebook/Podfile.lock
IdentitySdkGoogle/Podfile.lock
IdentitySdkWebView/Podfile.lock
Sandbox/Podfile.lock
Sandbox/Sandbox/ProfileController.swift

https://app.asana.com/0/980131104682803/1144219209743325/f

Fix http errors

---

IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePasswordLess.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/StartPasswordlessRequest.swift
Sandbox/Podfile.lock
Sandbox/Sandbox/PasswordlessController.swift

[Asana ticket](https://app.asana.com/0/980131104682803/1140896639771939/f)

Passwordless redirect_uri param configurable

---

.gitignore
IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePasswordLess.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/VerifyAuthCodeRequest.swift
Sandbox/Sandbox/Base.lproj/Main.storyboard
Sandbox/Sandbox/PasswordlessController.swift
Sandbox/Sandbox/UpdatePasswordController.swift

[Asana ticket](https://app.asana.com/0/980131104682803/1178704067546858/f)

Passwordless verify redirect_uri param configurable

---

IdentitySdkCore/IdentitySdkCore/Classes/models/ProviderConfig.swift

Removes unused value in providers config.

fix: remove unused config value

---

IdentitySdkCore/IdentitySdkCore/Classes/ReachFive.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePasswordLess.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveProviders.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/SdkConfig.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/AuthCodeRequest.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/RefreshRequest.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/VerifyAuthCodeRequest.swift
IdentitySdkWebView/IdentitySdkWebView/Classes/WebViewProvider.swift
README.md
Sandbox/Sandbox/AppDelegate.swift
Sandbox/Sandbox/Base.lproj/Main.storyboard
Sandbox/Sandbox/Info.plist
Sandbox/Sandbox/PasswordlessController.swift

[Asana ticket](https://app.asana.com/0/1108828962586858/1178242432075286/f)

Configure scheme with client ID

---

IdentitySdkCore/IdentitySdkCore/Classes/models/AuthToken.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/OpenIdUser.swift
IdentitySdkFacebook/Podfile.lock
IdentitySdkGoogle/Podfile.lock
IdentitySdkWebView/Podfile.lock
Sandbox/Podfile.lock

[Asana ticket](https://app.asana.com/0/1188236176227481/1189270592088985) in fast lane.

Add intermediary JSON object to deserialize `id` from `sub` in ID token

---

IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveError.swift

[[SDK iOS] Rajouter les error message key dans les error bodies](https://app.asana.com/0/980131104682803/1160053512301235/f)

Add errorMessageKey to ApiError.

---

IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveApi.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePassword.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/Profile.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/ProfileSignupRequest.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/SignupRequest.swift
Sandbox/Sandbox.xcodeproj/project.pbxproj
Sandbox/Sandbox.xcodeproj/xcshareddata/xcschemes/Sandbox.xcscheme
Sandbox/Sandbox/Base.lproj/Main.storyboard
Sandbox/Sandbox/Info.plist
Sandbox/Sandbox/SignupController.swift

Asana Task : https://app.asana.com/0/1141396442496489/1199342593301363

Add redirect url

---

IdentitySdkFacebook.podspec
IdentitySdkFacebook/Podfile
IdentitySdkFacebook/Podfile.lock
Sandbox/Podfile.lock

Asana task : https://app.asana.com/0/1198995533452093/1199895412250645

update facebook SDK version

---

IdentitySdkCore/IdentitySdkCore/Classes/ReachFive.swift
Sandbox/Sandbox/LoginWithFidoViewController.swift
Sandbox/Sandbox/SignUpFidoControllerViewController.swift

Asana Task : https://app.asana.com/0/1141396442496489/1200152170442333

add error-handling

---

IdentitySdkGoogle.podspec
IdentitySdkGoogle/IdentitySdkGoogle/Classes/GoogleProvider.swift
IdentitySdkGoogle/Podfile
Sandbox/Podfile.lock
Sandbox/Sandbox/LoginWithProvidersController.swift

[Asana](https://app.asana.com/0/1128361015731305/1200402216798000/f)
Migrate to major version 5 according to [the documentation](https://developers.google.com/identity/sign-in/ios/quick-migration-guide?hl=fr)

Upgrade GoogleSignIn to 5.0.2

---

IdentitySdkCore/IdentitySdkCore/Classes/ReachFive.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveApi.swift
Sandbox/Sandbox/LoginWithFidoViewController.swift
Sandbox/Sandbox/ProfileController.swift
Sandbox/Sandbox/SignUpFidoControllerViewController.swift

Les développements de Selim sont à tester avant la mise à disposition publique.
Pour info `internal` ça veut dire visibilité limitée à l'intérieur du module/framework.

Masquage des fonctions non testées

---

IdentitySdkGoogle.podspec
IdentitySdkGoogle/IdentitySdkGoogle.xcodeproj/project.pbxproj
IdentitySdkGoogle/IdentitySdkGoogle/Classes/GoogleProvider.swift
IdentitySdkGoogle/Podfile
IdentitySdkGoogle/Podfile.lock
Sandbox/Podfile.lock
Sandbox/Sandbox.xcodeproj/project.pbxproj

[Jira](https://reach5.atlassian.net/browse/CA-1532)
Attention, le viewController dans login est maintenant obligatoire.

[CA-1532] Mise à jour Google Sign In en version 6

---

IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveApi.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePassword.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/Profile.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/LoginRequest.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/ProfileSignupRequest.swift
IdentitySdkGoogle/Podfile.lock
Sandbox/Podfile.lock
Sandbox/Sandbox/Base.lproj/Main.storyboard
Sandbox/Sandbox/LoginWithPasswordController.swift

[[SDK iOS] ETQ user je veux m'authentifier avec le champ custom_identifier](https://reach5.atlassian.net/browse/CA-1782)
Possibilité de se loguer avec le custom identifier. Ce dernier est aussi renvoyé par défaut lors du chargement d'un profil et de toute opération renvoyant un profil.

[CA-1782] Possibilité de se loguer avec le custom identifier/mot de passe

---

IdentitySdkCore/IdentitySdkCore/Classes/LoginWKWebview.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveLogin.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePassword.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePasswordLess.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveWebviewLogin.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/LoginCallback.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/LoginRequest.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/SignupRequest.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/StartPasswordlessRequest.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/VerifyAuthCodeRequest.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/WebviewLoginRequest.swift
IdentitySdkWebView/IdentitySdkWebView/Classes/WebViewProvider.swift
Sandbox/Sandbox/ActionController.swift
Sandbox/Sandbox/DemoController.swift
Sandbox/Sandbox/LoginCustomWebviewController.swift
Sandbox/Sandbox/LoginWKWebviewController.swift
Sandbox/Sandbox/LoginWithPasswordController.swift
Sandbox/Sandbox/LoginWithProvidersController.swift
Sandbox/Sandbox/NativePasswordController.swift
Sandbox/Sandbox/PasswordlessController.swift
Sandbox/Sandbox/SignupController.swift

[Ajouter "Origin" dans WebViewLogin](https://reach5.atlassian.net/browse/CA-2966)
Endroits où ça a été ajouté : 
- signup (avec mot de passe)
- loginWithPassword
- loginCallback
- startPasswordless
- verifyPasswordlessCode
- webviewLogin
- WebViewProvider.login
- loadLoginWebview

[CA-2966] Ajout des origines

---

IdentitySdkCore/IdentitySdkCore/Classes/models/ProfileAddress.swift

[Jira](https://reach5.atlassian.net/browse/CA-3358)

[CA-3358] Support address custom fields

---

IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveApi.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveMfa.swift
Sandbox/Sandbox/MfaController.swift

https://reach5.atlassian.net/browse/CA-3480

[CA-3480] mfa credential verify regstering returns the credential

---

IdentitySdkCore/IdentitySdkCore.xcodeproj/project.pbxproj
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveApi.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveMfa.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/MfaStepUpRequest.swift
IdentitySdkCore/IdentitySdkCore/Classes/models/requests/StartPasswordlessRequest.swift
Sandbox/Sandbox/Base.lproj/Main.storyboard
Sandbox/Sandbox/MfaController.swift

https://reach5.atlassian.net/browse/CA-3414

[CA-3414] Adds step up methods

---

IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveApi.swift
IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveMfa.swift
Sandbox/Sandbox/MfaController.swift

https://reach5.atlassian.net/browse/CA-3410

[CA-3410] delete MFA credential
